version: '3'

services:
  server:
    build: .
    container_name: sample
    restart: always
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - ./:/data
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
  mongo:
    container_name: mongodb-dev
    image: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./database/db:/data/db